### PR TITLE
Create main server file

### PR DESCRIPTION
**Pull request by SharkFinPro**
(use this as the file for the server)

### CODE REVIEW

**Comment by SharkFinPro** [comment]
Discard this if you are currently developing @Andrews54757

**Comment by LegitSoulja** [comment]
@SharkFinPro I don't think andrew will continue with this project.

**Comment by Andrews54757** [comment]
@LegitSoulja I am developing some of it. It will be an interesting side project

**Comment by segg21** [comment]
@Andrews54757 yea, i didn't see the state (recent commits) of the repo at first.

Also, did you ever look at this? https://github.com/AJS-development/OAPluginCompiler/issues/1

**Comment by Andrews54757** [comment]
@LegitSoulja No, I havent looked. I am going to now

**Comment by SharkFinPro** [comment]
@Andrews54757 any progress? LOL

**Pull request merged**
